### ISSUE TITLE
REJECT_OUTBOUND and ADD_ONLINE_REPOS to support values with or without quotes for offline PNDA deployment

### ISSUE THREAD

**Issue by smaniramkrish** [pndaproject/pnda-aws-templates#147]
For PNDA offline deployment currently under connectivity section REJECT_OUTBOUND and ADD_ONLINE_REPOS values in the pnda.yaml  without quotes as YES/NO doesn't add reject iptable rules in the created instances. Reject IP tables is added for values 'YES' 'NO' with quotes

Expectation: If the value YES and NO provided with or without quotes it should add reject iptables rules in the instances

**Comment by trsmith2** [comment]
The conversion of certain key words for scalar formats in this way is documented in YAML 1.1. Therefore, we now quote the example.
