### ISSUE TITLE
For REJECT_OUTBOUND iptables is hard coded 10.0.0.0/16 in package-install.sh

### ISSUE THREAD

**Issue by smaniramkrish** [pndaproject/pnda-aws-templates#148]
In package-install.sh, script is adding an entry as mentioned below. But if a user changes the PNDA network in pnda.yaml  might fail. Not done the deployment with the change. This is tracking purpose to fix it in future

iptables -A LOGGING -d  10.0.0.0/16 -j ACCEPT # PNDA network

**Comment by trsmith2** [comment]
Thanks, yes this is an issue

**Comment by trsmith2** [comment]
pnda-aws-templates is no longer supported
