### ISSUE TITLE
Ubuntu - REJECT OUTBOUND and ADD_ONLINE_REPOS as YES IPTable is not getting updated

### ISSUE THREAD

**Issue by smaniramkrish** [pndaproject/pnda-aws-templates#149]
In package-install.sh for ADD_ONLINE_REPOS = YES and REJECT OUTBOUND = YES for Ubuntu, code is adding keys and sources.list for the cloudera, saltstack sites. But the IPtables aren't adding ACL entries for these websites. 

Not done the deployment with the change. This is tracking purpose to fix it in future

**Comment by trsmith2** [comment]
Since the purpose of REJECT_OUTBOUND is simply to simulate an air gapped environment it makes little sense to do this. If anything, warning and rejecting the on the YES/YES combination would be preferable.

**Comment by trsmith2** [comment]
pnda-aws-templates is no longer supported
