### ISSUE TITLE
Ubuntu offline mode package install issue

### ISSUE THREAD

**Issue by janselva** [pndaproject/pnda-aws-templates#151]
SaltStack trying to upgrade the packages using the pkg.uptodate state but it’s not failed, 
Because it’s not able to download the libcgmanager0 and screen from global server

While checking the apt policy, latest versions point to global mirrors, instead of local mirror server.

bastion:/home/ubuntu# apt-cache policy libcgmanager0
libcgmanager0:
  Installed: 0.24-0ubuntu7.5
  Candidate: 0.39-2ubuntu2~ubuntu14.04.1
  Version table:
     _**# 0.39-2ubuntu2~ubuntu14.04.1 0**_
        500 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-backports/main amd64 Packages
_**#  0.24-0ubuntu7.5 0<<Current version installed on the system>>**_
        500 http://34.215.51.80/ubuntu/develop//mirror_deb/ ./ Packages  <<<Local Mirror server >>
        500 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     0.24-0ubuntu7.1 0
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
     0.24-0ubuntu5 0
        500 http://us-west-2.ec2.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages

**Comment by trsmith2** [comment]
Please refer to https://github.com/pndaproject/pnda-cli
